#ifndef BORROWING_DIALOGS_H
#define BORROWING_DIALOGS_H

#define IDD_ADD_BORROWING       7000
#define IDD_RETURN_BOOK         7001

#define IDC_BORROWING_BOOK_ID   7002
#define IDC_BORROWING_MEMBER_ID 7003
#define IDC_BORROWING_STAFF_ID  7004
#define IDC_BORROWING_BORROW_DATE 7005
#define IDC_BORROWING_DUE_DATE  7006
#define IDC_BORROWING_ID        7007 // For return dialog
#define IDC_BORROWING_RETURN_DATE 7008

#endif // BORROWING_DIALOGS_H 