#ifndef MEMBER_DIALOGS_H
#define MEMBER_DIALOGS_H

#define IDD_ADD_MEMBER      5000
#define IDD_EDIT_MEMBER     5001

#define IDC_MEMBER_NAME     5002
#define IDC_MEMBER_ADDRESS  5003
#define IDC_MEMBER_PHONE    5004
#define IDC_MEMBER_EMAIL    5005
#define IDC_MEMBER_DATE_JOINED 5006
#define IDC_MEMBER_MEMBERSHIP_STATUS 5007
#define IDC_MEMBER_ID       5008

#endif // MEMBER_DIALOGS_H 