#ifndef PUBLISHER_DIALOGS_H
#define PUBLISHER_DIALOGS_H

#define IDD_ADD_PUBLISHER      4000
#define IDD_EDIT_PUBLISHER     4001

#define IDC_PUBLISHER_NAME     4002
#define IDC_PUBLISHER_ADDRESS  4003
#define IDC_PUBLISHER_CONTACT  4004
#define IDC_PUBLISHER_ID       4005

#endif // PUBLISHER_DIALOGS_H 